pipeline:
    build:
       image: 10.1.86.51/devops/golang:1.7-godep
       commands:
            #         - echo LABEL commit-sha=${DRONE_COMMIT_SHA} commit-message=${DRONE_COMMIT_MESSAGE/\n/-} branch=${DRONE_COMMIT_BRANCH} build-number=${DRONE_BUILD_NUMBER} >> Dockerfile
         - mkdir -p $GOPATH/src/github.com/docker/swarm/ && cp -r ./* $GOPATH/src/github.com/docker/swarm/ && pwd
         - cd $GOPATH/src/github.com/docker/swarm/ && godep go build -o cattle && cd - && cp $GOPATH/src/github.com/docker/swarm/cattle .

    publish:
          image: plugins/docker
          username: admin
          password: Harbor12345
          registry: 10.1.86.51
          email: fhtjob@hotmail.com
          repo: 10.1.86.51/devops/cattle
          tag: beta-v1.2.6.1
          file: Dockerfile
          insecure: true
