pipeline:
    build:
       image: 10.1.86.51/devops/golang:1.7-godep
       commands:
         - mkdir -p $GOPATH/src/github.com/docker/swarm/ && cp -r ./* $GOPATH/src/github.com/docker/swarm/ && pwd
         - cd $GOPATH/src/github.com/docker/swarm/ && godep go build -o cattle && cd - && cp $GOPATH/src/github.com/docker/swarm/cattle .

    publish:
          image: plugins/docker
          username: admin
          password: Harbor12345
          registry: 10.1.86.51
          email: fhtjob@hotmail.com
          repo: 10.1.86.51/devops/cattle
          tag: alpha-v1.2.6.1
          file: Dockerfile
          insecure: true

#   upload:
#       image: dev.reg.iflytek.com/test/ci-sftp
#       repo: dev.reg.iflytek.com/devops/cattle:alpha-v1.2.6.1
#       dockerengine: 10.1.86.206
#       sftpaddr: 172.16.12.214
#       sftpuser: chenqian
#       sftppasswd: iflyteksftp
#       sftpdir: images
